#!/usr/bin/env node
/**
 * Cougr design tokens build.
 *
 * Reads `tokens.json` (the single source of truth, mirroring docs/BRAND.md) and
 * writes two generated artifacts into `dist/`:
 *
 *   dist/tokens.css  CSS custom properties, for any static HTML/CSS consumer.
 *   dist/tokens.js   an ESM module, for consumers that need literal values at
 *                    build time rather than at CSS resolution time.
 *
 * Usage:
 *   node build.js            build dist/
 *   node build.js --check    validate the source and a dry-run build, write nothing
 *
 * `dist/` is generated, never committed. It is produced on demand by `npm run
 * build`, and automatically on install or publish by the `prepare` script.
 *
 * Zero dependencies, so it runs with a bare `node` and no install step.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.join(__dirname, 'tokens.json');
const DIST = path.join(__dirname, 'dist');
const BRAND_DOC = path.join(__dirname, '..', '..', 'docs', 'BRAND.md');

const BANNER = 'Generated by packages/tokens/build.js from tokens.json. Do not edit by hand.';

/** `color-text-secondary` -> `colorTextSecondary`, `space-1` -> `space1`. */
function camelCase(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/**
 * Split the token table into the two shapes the outputs need:
 *   shared  tokens with one value in both modes
 *   themed  tokens with a distinct light and dark value
 */
function partition(tokens) {
  const shared = [];
  const themed = [];

  for (const [name, spec] of Object.entries(tokens)) {
    const hasModes = 'light' in spec || 'dark' in spec;

    if (hasModes) {
      if (!spec.light || !spec.dark) {
        throw new Error(`Token "${name}" defines one mode only; both light and dark are required.`);
      }
      themed.push({ name, light: spec.light, dark: spec.dark, comment: spec.comment });
    } else {
      if (spec.value === undefined) {
        throw new Error(`Token "${name}" has neither a light/dark pair nor a "value".`);
      }
      shared.push({ name, value: spec.value, comment: spec.comment });
    }
  }

  return { shared, themed };
}

function declarations(entries, pick, indent) {
  return entries
    .map(({ name, ...rest }) => `${indent}--${name}: ${pick(rest)};`)
    .join('\n');
}

function buildCss({ version, shared, themed }) {
  const sharedDecls = declarations(shared, (t) => t.value, '  ');
  const lightDecls = declarations(themed, (t) => t.light, '  ');
  const darkMediaDecls = declarations(themed, (t) => t.dark, '    ');
  const darkDecls = declarations(themed, (t) => t.dark, '  ');
  const lightOverrideDecls = declarations(themed, (t) => t.light, '  ');

  return `/*
 * Cougr design tokens v${version}
 * ${BANNER}
 *
 * Theming contract:
 *   Light is the default. Dark applies automatically when the reader's system
 *   prefers it, unless the document has opted out with data-theme="light".
 *   An explicit data-theme attribute on the root element always wins.
 */

:root {
${sharedDecls}

${lightDecls}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${darkMediaDecls}
  }
}

:root[data-theme='dark'] {
${darkDecls}
}

:root[data-theme='light'] {
${lightOverrideDecls}
}
`;
}

function jsObject(entries, pick) {
  return entries
    .map(({ name, ...rest }) => `  ${camelCase(name)}: ${JSON.stringify(pick(rest))},`)
    .join('\n');
}

function buildJs({ version, shared, themed }) {
  const sharedProps = jsObject(shared, (t) => t.value);
  const lightProps = jsObject(themed, (t) => t.light);
  const darkProps = jsObject(themed, (t) => t.dark);

  return `/*
 * Cougr design tokens v${version}
 * ${BANNER}
 *
 * For consumers that need literal token values at build time: anything
 * producing standalone artifacts (SVG, PNG, terminal output) where CSS custom
 * properties cannot be resolved. Static HTML/CSS consumers should import
 * dist/tokens.css instead.
 */

export const version = '${version}';

/** Tokens whose value is the same in both modes. */
export const shared = Object.freeze({
${sharedProps}
});

export const light = Object.freeze({
  ...shared,
${lightProps}
});

export const dark = Object.freeze({
  ...shared,
${darkProps}
});

export const tokens = Object.freeze({ light, dark });

/** Resolve a mode by name, defaulting to light. */
export function theme(mode) {
  return mode === 'dark' ? dark : light;
}

export default tokens;
`;
}

/**
 * Confirm the token source still says what docs/BRAND.md says.
 *
 * BRAND.md is the source of truth; this file only encodes it. Nothing stops the
 * two drifting apart by hand, so every colour and every scale value documented
 * there has to be present here. This is the guarantee that used to come from
 * diffing a committed `dist/`, moved to where the actual risk is.
 */
function verifyAgainstBrandDoc(source) {
  if (!fs.existsSync(BRAND_DOC)) {
    return [`docs/BRAND.md not found at ${BRAND_DOC}`];
  }

  const doc = fs.readFileSync(BRAND_DOC, 'utf8');
  const encoded = JSON.stringify(source.tokens).toUpperCase();
  const problems = [];

  const documentedColors = [...new Set((doc.match(/#[0-9A-Fa-f]{6}\b/g) || []).map((h) => h.toUpperCase()))];
  const missingColors = documentedColors.filter((hex) => !encoded.includes(hex));
  if (missingColors.length > 0) {
    problems.push(`colours in docs/BRAND.md but not in tokens.json: ${missingColors.join(', ')}`);
  }

  // Table rows of the form: | `space-1` | 4px |
  for (const [, name, value] of doc.matchAll(/\|\s*`((?:space|radius)-[a-z0-9]+)`\s*\|\s*(\S+?)\s*\|/g)) {
    const token = source.tokens[name];
    if (!token) {
      problems.push(`${name} is documented in docs/BRAND.md but missing from tokens.json`);
    } else if (token.value !== value) {
      problems.push(`${name} is ${value} in docs/BRAND.md but ${token.value} in tokens.json`);
    }
  }

  return problems;
}

function main() {
  const check = process.argv.includes('--check');

  const source = JSON.parse(fs.readFileSync(SOURCE, 'utf8'));
  const { version } = source;
  if (!version) {
    console.error('tokens.json is missing a "version" field.');
    process.exit(1);
  }

  const { shared, themed } = partition(source.tokens);
  const outputs = {
    'tokens.css': buildCss({ version, shared, themed }),
    'tokens.js': buildJs({ version, shared, themed }),
  };

  if (check) {
    // Building the outputs above already enforced the structural rules: every
    // themed token carries both modes, every shared token carries a value.
    const problems = verifyAgainstBrandDoc(source);

    if (problems.length > 0) {
      console.error('Token source does not match docs/BRAND.md:');
      for (const problem of problems) console.error(`  - ${problem}`);
      console.error('\nBRAND.md is the source of truth. Update it first, then mirror it in tokens.json.');
      process.exit(1);
    }

    for (const [file, contents] of Object.entries(outputs)) {
      if (!contents.trim()) {
        console.error(`Generated ${file} is empty.`);
        process.exit(1);
      }
    }

    console.log(`✓ tokens.json v${version} matches docs/BRAND.md and builds cleanly`);
    console.log(`  ${shared.length} shared + ${themed.length} themed tokens, nothing written`);
    return;
  }

  fs.mkdirSync(DIST, { recursive: true });
  for (const [file, contents] of Object.entries(outputs)) {
    fs.writeFileSync(path.join(DIST, file), contents, 'utf8');
    console.log(`✓ Written dist/${file}`);
  }
  console.log(`  ${shared.length} shared + ${themed.length} themed tokens (v${version})`);
}

main();
