name: Chess Example CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/chess/**'
      - '!examples/chess/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/chess.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/chess/**'
      - '!examples/chess/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/chess.yml'

concurrency:
  group: chess-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Chess Example CI
      working_directory: examples/chess
