name: Season Ladder Example CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/season_ladder/**'
      - '!examples/season_ladder/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/season_ladder.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/season_ladder/**'
      - '!examples/season_ladder/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/season_ladder.yml'

concurrency:
  group: season_ladder-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Season Ladder Example CI
      working_directory: examples/season_ladder
